import type { DashboardLanguage } from "../../localization/languages";

const en = {
  title: "Wakeup Tasks",
  add: "Add Task",
  edit: "Edit Task",
  create: "New Wakeup Task",
  tasks: "Tasks",
  history: "History",
  back: "Back",
  close: "Close",
  save: "Save Task",
  cancel: "Cancel",
  automation: "Scheduled wakeups",
  enabled: "On",
  disabled: "Off",
  waitingForEnable: "Waiting for master switch",
  waitingForRun: "Scheduled",
  taskPaused: "Task paused",
  automationOff: "Scheduled wakeups are off",
  enableAll: "Enable scheduled wakeups",
  pauseAll: "Pause scheduled wakeups",
  description: "Send a short Codex request at your chosen time to start a quota window.",
  note: "Uses a small amount of quota. Keep at least one VS Code window open; missed runs older than 5 minutes are skipped.",
  empty: "No wakeup tasks yet",
  emptyHint: "Choose accounts and a time. You can test a task before enabling the schedule.",
  name: "Task name",
  namePlaceholder: "Morning wakeup",
  time: "Time",
  schedule: "Schedule",
  calendar: "Time & weekdays",
  interval: "Fixed interval",
  intervalValue: "Repeat every",
  intervalUnit: "Interval unit",
  hours: "hours",
  minutes: "minutes",
  intervalSummary: "Every {value} {unit}",
  intervalHint:
    "The first run is one interval after saving or resuming this task. Run Now does not change the schedule.",
  days: "Repeat",
  daily: "Every day",
  weekdays: "Weekdays",
  accounts: "Accounts",
  search: "Search accounts",
  selectAll: "Select all",
  clear: "Clear",
  noAccounts: "No matching saved accounts",
  model: "Model",
  customModel: "Custom model ID…",
  modelId: "Model ID",
  modelHint: "Choose a model available to the selected accounts. Use Custom model ID for models outside this list.",
  modelRetirement: "GPT-5.5 retirement in Codex: 2026-10-14. Choose an available replacement.",
  effort: "Reasoning effort",
  prompt: "Prompt",
  run: "Run Now",
  running: "Running",
  pause: "Pause Task",
  resume: "Enable Task",
  remove: "Delete",
  confirmRemove: "Confirm deletion",
  next: "Next run",
  last: "Last run",
  never: "Not run yet",
  scheduled: "Scheduled",
  manual: "Manual",
  accountCount: "accounts",
  noHistory: "No execution history yet",
  success: "success",
  failed: "failed",
  details: "Account results",
  accountSelectError: "Select at least one account.",
  selectError: "Select at least one account and weekday.",
  saved: "Task saved",
  updated: "Schedule updated",
  runFinished: "Run finished. See the account results in History.",
  localTime: "Local time",
  pausedHint:
    "Scheduled wakeups are off. Saved tasks will run after you turn on the master switch. Run Now remains available.",
  statuses: {
    running: "Running",
    success: "Success",
    partial: "Partial success",
    failed: "Failed",
    cancelled: "Cancelled",
    interrupted: "Interrupted; not replayed",
    missed: "Missed; skipped"
  }
};

const zh: typeof en = {
  title: "唤醒任务",
  add: "添加任务",
  edit: "编辑任务",
  create: "新建唤醒任务",
  tasks: "任务",
  history: "执行历史",
  back: "返回",
  close: "关闭",
  save: "保存任务",
  cancel: "取消",
  automation: "定时唤醒",
  enabled: "已开启",
  disabled: "已关闭",
  waitingForEnable: "待开启定时",
  waitingForRun: "等待执行",
  taskPaused: "任务已暂停",
  automationOff: "定时唤醒已关闭",
  enableAll: "开启定时唤醒",
  pauseAll: "暂停定时唤醒",
  description: "在指定时间发送一条简短的 Codex 请求。",
  note: "会使用少量额度。需保持至少一个 VS Code 窗口运行；错过超过 5 分钟的任务会跳过。",
  empty: "还没有唤醒任务",
  emptyHint: "选择账号和时间，也可以先立即测试，再开启定时唤醒。",
  name: "任务名称",
  namePlaceholder: "早间唤醒",
  time: "执行时间",
  schedule: "调度方式",
  calendar: "指定时间和星期",
  interval: "固定间隔",
  intervalValue: "每隔",
  intervalUnit: "间隔单位",
  hours: "小时",
  minutes: "分钟",
  intervalSummary: "每隔 {value} {unit}",
  intervalHint: "保存或恢复任务后，等待一个间隔再执行首次唤醒；立即测试不改变定时周期。",
  days: "重复日期",
  daily: "每天",
  weekdays: "工作日",
  accounts: "选择账号",
  search: "搜索账号",
  selectAll: "全选",
  clear: "清空",
  noAccounts: "没有匹配的已保存账号",
  model: "模型",
  customModel: "自定义模型 ID…",
  modelId: "模型 ID",
  modelHint: "选择所选账号可用的模型；列表外的模型可使用“自定义模型 ID”。",
  modelRetirement: "GPT-5.5 在 Codex 的下线日期为 2026-10-14，建议选择其他可用模型。",
  effort: "推理强度",
  prompt: "唤醒提示词",
  run: "立即测试",
  running: "执行中",
  pause: "暂停任务",
  resume: "启用任务",
  remove: "删除",
  confirmRemove: "确认删除",
  next: "下次执行",
  last: "上次执行",
  never: "尚未执行",
  scheduled: "定时",
  manual: "手动",
  accountCount: "个账号",
  noHistory: "还没有执行记录",
  success: "成功",
  failed: "失败",
  details: "账号执行结果",
  accountSelectError: "请至少选择一个账号。",
  selectError: "请至少选择一个账号和一个执行日期。",
  saved: "任务已保存",
  updated: "定时设置已更新",
  runFinished: "执行已结束，可在执行历史中查看各账号的结果。",
  localTime: "本机时间",
  pausedHint: "定时唤醒已关闭。任务已保存，打开总开关后按设定时间执行；仍可立即测试。",
  statuses: {
    running: "执行中",
    success: "成功",
    partial: "部分成功",
    failed: "失败",
    cancelled: "已取消",
    interrupted: "已中断，不自动重试",
    missed: "已错过，跳过执行"
  }
};

export function getWakeupCopy(lang: DashboardLanguage): typeof en {
  return lang === "zh" || lang === "zh-hant" ? zh : en;
}
